// --------------------------------------------------------

// Code generated by Papyrus Java

// --------------------------------------------------------



package assignment1;



/************************************************************/

/**

 * 

 */

class Board {

	/**

	 * 

	 */

	private Map<Integer, HexTerrain> tiles;

	/**

	 * 

	 */

	private assignment1.Board.Map<Integer, Intersection> intersections;

	/**

	 * 

	 */

	private Building[] buildings;

	/**

	 * 

	 */

	private int[] tilesNodes;

	/**

	 * 

	 */

	private assignment1.Board.Map<Integer, List<Integer>> adjacency;

	/**

	 * 

	 */

	private int builtRoads;



	/**

	 * 

	 */

	public void Board() {

	}



	/**

	 * 

	 * @return 

	 * @param isValidEdge 

	 * @param isValidEdge 

	 */

	public boolean isValidEdge(int isValidEdge, int isValidEdge) {

	}



	/**

	 * 

	 * @param getNeighbouringIntersections 

	 * @param getneighbouringIntersections 

	 */

	public void getNeighbouringIntersections(int getNeighbouringIntersections, int[] getneighbouringIntersections) {

	}



	/**

	 * 

	 * @param getIntersection 

	 * @return 

	 */

	public Intersection getIntersection(int getIntersection) {

	}



	/**

	 * 

	 * @param placeSettlement 

	 * @param placeSettlement 

	 * @return 

	 */

	public boolean placeSettlement(Intersection placeSettlement, undef placeSettlement) {

	}



	/**

	 * 

	 * @param placeCity 

	 * @param placeCity 

	 * @return 

	 */

	public boolean placeCity(undef placeCity, Intersection placeCity) {

	}



	/**

	 * 

	 * @param placeRoad 

	 * @param placeRoad 

	 * @return 

	 */

	public boolean placeRoad(Edge placeRoad, undef placeRoad) {

	}



	/**

	 * 

	 * @return 

	 */

	public HexTerrain[] getHexes() {

	}



	/**

	 * 

	 * @param getHex 

	 */

	public void getHex(int getHex) {

	}



	/**

	 * 

	 * @return 

	 * @param gethexIntersections 

	 */

	public int[] getHexIntersections(int gethexIntersections) {

	}

}


// --------------------------------------------------------

// Code generated by Papyrus Java

// --------------------------------------------------------



package assignment1;



/************************************************************/

/**

 * 

 */

public abstract class Building extends Settlement {

	/**

	 * 

	 */

	protected undef buildingOwner;

	/**

	 * 

	 */

	protected Intersection buildingLocation;

	/**

	 * 

	 */

	public Intersection intersection;



	/**

	 * 

	 * @return 

	 */

	public abstract Intersection getBuildingLocation();



	/**

	 * 

	 * @return 

	 */

	public void getOwner() {

	}



	/**

	 * 

	 * @param buildingIntersection 

	 * @param Building 

	 */

	public void Building(Intersection buildingIntersection, undef Building) {

	}



	/**

	 * 

	 * @return 

	 */

	public abstract int getVictoryPoints();

}


// --------------------------------------------------------

// Code generated by Papyrus Java

// --------------------------------------------------------



package assignment1;



/************************************************************/

/**

 * 

 */

public class City {

	/**

	 * 

	 * @return 

	 */

	public int getVictoryPoints() {

	}



	/**

	 * 

	 * @param cityIntersection 

	 * @param owner 

	 */

	public void City(Intersection cityIntersection, undef owner) {

	}

}


// --------------------------------------------------------

// Code generated by Papyrus Java

// --------------------------------------------------------



package assignment1;



/************************************************************/

/**

 * 

 */

public class GameRules {

	/**

	 * 

	 */

	private int[] tilesNodes;

	/**

	 * 

	 */

	public Board board;



	/**

	 * 

	 * @param checkBuildingPlacement 

	 * @param checkBuildingPlacement 

	 * @param checkBuildingPlacement 

	 * @return 

	 */

	public boolean checkBuildingPlacement(int checkBuildingPlacement, undef checkBuildingPlacement,

			Board checkBuildingPlacement) {

	}



	/**

	 * 

	 * @param checkEmptyIntersection 

	 * @param checkEmptyIntersection 

	 * @param checkEmptyIntersection 

	 */

	public void checkEmptyIntersection(int checkEmptyIntersection, Board checkEmptyIntersection,

			boolean checkEmptyIntersection) {

	}



	/**

	 * 

	 * @param isConnected 

	 * @param isConnected 

	 * @param isConnected 

	 * @return 

	 */

	public boolean isConnected(Intersection isConnected, undef isConnected, Board isConnected) {

	}



	/**

	 * 

	 * @param checkRoadPlacement 

	 * @param checkRoadPlacement 

	 * @param checkRoadPlacement 

	 * @return 

	 */

	public boolean checkRoadPlacement(Edge checkRoadPlacement, undef checkRoadPlacement, Board checkRoadPlacement) {

	}

}


// --------------------------------------------------------

// Code generated by Papyrus Java

// --------------------------------------------------------



package assignment1;



/************************************************************/

/**

 * 

 */

public class Intersection {

	/**

	 * 

	 */

	private undef owner;

	/**

	 * 

	 */

	private Building intersectionBuilding;

	/**

	 * 

	 */

	public int intersectionID;

	/**

	 * 

	 */

	public Building building;

	/**

	 * 

	 */

	public Board board;



	/**

	 * 

	 * @return 

	 */

	public int getIntersectionLocation() {

	}



	/**

	 * 

	 * @param building 

	 */

	public void setBuilding(Building building) {

	}



	/**

	 * 

	 * @param node 

	 */

	public void Intersection(int node) {

	}



	/**

	 * 

	 * @param player 

	 */

	public void setOwner(undef player) {

	}



	/**

	 * 

	 * @return 

	 */

	public Building getBuilding() {

	}



	/**

	 * 

	 * @return 

	 */

	public void getPlayer() {

	}

}


// --------------------------------------------------------

// Code generated by Papyrus Java

// --------------------------------------------------------



package assignment1;



/************************************************************/

/**

 * 

 */

public class Road {

	/**

	 * 

	 */

	private undef owner;

	/**

	 * 

	 */

	private Edge location;



	/**

	 * 

	 * @param owner 

	 * @param location 

	 */

	public void Road(undef owner, Edge location) {

	}



	/**

	 * 

	 * @return 

	 */

	public Edge getLocation() {

	}



	/**

	 * 

	 * @return 

	 */

	public void getOwner() {

	}

}


// --------------------------------------------------------

// Code generated by Papyrus Java

// --------------------------------------------------------



package assignment1;



/************************************************************/

/**

 * 

 */

public class Settlement {

	/**

	 * 

	 * @param settlementIntersection 

	 * @param owner 

	 */

	public void Settlement(Intersection settlementIntersection, undef owner) {

	}



	/**

	 * 

	 * @return 

	 */

	public int getVictoryPoints() {

	}

}


// --------------------------------------------------------

// Code generated by Papyrus Java

// --------------------------------------------------------



package assignment1;



/************************************************************/

/**

 * 

 */

public class Simulator {

	/**

	 * 

	 */

	private int maxRounds;

	/**

	 * 

	 */

	private undef players;

	/**

	 * 

	 */

	private Turn turn;



	/**

	 * 

	 */

	public void runGame() {

	}

}


// --------------------------------------------------------

// Code generated by Papyrus Java

// --------------------------------------------------------



package assignment1;



/************************************************************/

/**

 * 

 */

public class Turn {

	/**

	 * 

	 */

	private Dice dice;

	/**

	 * 

	 */

	private Production Production;

	/**

	 * 

	 */

	private Board board;

	/**

	 * 

	 */

	public Dice dice;

	/**

	 * 

	 */

	public Simulator simulator;



	/**

	 * 

	 * @param Turn 

	 * @param Turn 

	 * @param Board 

	 */

	public void Turn(Dice Turn, Production Turn, Board Board) {

	}



	/**

	 * 

	 * @param execute 

	 * @param execute 

	 * @return 

	 */

	public String execute(undef execute, int execute) {

	}

}

